spring:
  kafka:
    consumer:
      group-id: clean-arch-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: org.example.usecases
    bootstrap-servers: localhost:9092