spring:
  profiles:
    active: postgres, kafka, email
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

app.email.from: from@email.com