spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25432/clean_arch
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        # Fix Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        temp:
          use_jdbc_metadata_defaults: false